import {
  Geist,
  Geist_Mono,
  BBH_Sans_Bogle,
  Roboto_Condensed,
} from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/ReactQueryProvider";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bbh-sans-bogle",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={robotoCondensed.variable}>
      <body className={robotoCondensed.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
